import type { PolicyDocument } from "./types";

export const termsPolicy: PolicyDocument = {
  badge: "Terms & Conditions",
  title: "Terms & Conditions",
  intro: [
    'Oweg, provides a collection of tools and resources to manage an online store, process orders and sell products online and other services (collectively, the "Services"). The following are the terms and conditions for use of the Services (the "Terms"), along with any amendments thereto and any operating rules or policies that may be published from time to time by Oweg, You agree that you have read and understand, and have the capacity and authority to accept, agree to and be bound by these Terms.',
  ],
  sections: [
    {
      title: "1. Service and Terms",
      bullets: [
        "The Services are provided subject to these Terms and any operating rules or policies that Oweg may publish from time to time. Oweg may make changes or modifications to this Agreement at any time, and such changes or modifications are effective immediately upon the earliest of (a) Oweg email notification to you advising you of such changes or modifications, (b) your electronic acceptance of this Agreement after such changes or modifications have been made to this Agreement as indicated by the \"Date of Last Revision\" date at the top of the Terms, or (c) your continued use of the Services after Oweg posts the updated Agreement to Oweg. In addition, when using particular Oweg services, Customer and Oweg will be subject to any posted guidelines or rules applicable to such Services that may be posted from time to time.",
        "The Services are available only to persons who can form legally binding contracts under applicable law. Without limiting the foregoing, the Services are not available to individuals under the age of 18. If you do not qualify, please do not use the Services.",
        "The Services provides a collection of tools and resources to manage an online store, process orders and sell products online. In addition, the Services may include migration services relating to your use of the Oweg tools and resources.",
        "Customer must complete a registration form in order to use the Services. Customer will provide true, accurate, current, and complete information about Customer as requested in the registration form, and will update the information to keep it current. As part of the registration process, Customer will identify an email address and password for Customer's Oweg account. Customer is responsible for maintaining the security of Customer's account, passwords, and files, and for all uses of Customer's account and of the Services in Customer's name. Oweg reserves the right to refuse registration of, or cancel, accounts it deems inappropriate.",
      ],
    },
    {
      title: "2. Restrictions and Responsibilities",
      bullets: [
        "Customer represents, covenants, and warrants that Customer will use the Services only in compliance with these Terms, Oweg published privacy policies or otherwise furnished to Customer (the \"Privacy Policy\") and all applicable laws (including but not limited to policies and laws related to spamming, privacy, obscenity, or defamation). Customer may not access or otherwise use third party mailing lists in connection with preparing or distributing unsolicited email to any third party. Customer hereby agrees to indemnify and hold harmless Oweg and its Content Providers and the respective directors, officers, employees and agents of each against any damages, losses, liabilities, settlements, and expenses (including without limitation costs and reasonable attorneys' fees) in connection with any claim or action that arises from an alleged violation of the foregoing. Although Oweg has no obligation to monitor the content provided by Customer or Customer's use of the Services, Oweg may do so and may remove any such content or prohibit any use of the Services it believes may be (or alleged to be) in violation of the foregoing.",
        "For every email message sent in connection with the Services, Customer acknowledges and agrees that the recipient has agreed to receive such communication and that Customer will not engage in the act of sending unsolicited emails.",
        "In using the varied features of the Services, Customer may provide information (such as name, contact information, or other registration information) to Oweg . Oweg may use this information and any technical information about Customer's use of this website to tailor its presentations to Customer, facilitate Customer's movement through this website, or communicate separately with Customer. Oweg will not provide information to companies Customer has not authorized, and Oweg Enterprises will not authorize the companies that get such information to sell and redistribute it without Customer's prior consent.",
        "Customer acknowledges and agrees that: (a) the Services including without limitation, any modifications, enhancements and updates, and any originals and copies thereof, in whole or in part, and all intellectual property rights therein (collectively, \"Proprietary Information\") are owned by Oweg Enterprises and/or its third party sponsors, partners, and other co-branders (collectively, \"Content Providers\"), (b) the Proprietary Information contains valuable copyrighted material and is protected by U.S. and international copyright and other intellectual property laws, (c) the Proprietary Information is licensed, rather than sold, to Customer pursuant to these Terms, and (d) Customer has no rights in the Proprietary Information, other than the rights and licenses granted to Customer herein.",
        "Oweg Trademarks. \"Oweg \" and our logos (both words and design) either are trademarks, service marks, or registered trademarks of Oweg or its Content Providers, and may not be copied, imitated or used, in whole or in part without Oweg prior express written consent or that of our Content Providers. In addition, all page headers, custom graphics, design and user interface elements, and scripts are service marks, trademarks, and/or trade dress of Oweg and may not be copied, imitated, or used, in whole or in part without our prior written permission, which consent may be withheld in our sole discretion. All other marks or logos not owned by Oweg are the property of their respective owners.",
        "Reservation of Rights. Except for the rights expressly granted to Customer pursuant to these Services, Customer acknowledges that it has no right, title or interest in or to this website, the Services or Proprietary Information. All rights not expressly granted by Oweg in these Terms are hereby reserved by Oweg Enterprises. There are no implied rights.",
      ],
    },
    {
      title: "3. Term and Termination",
      bullets: [
        "Oweg may terminate this Agreement or the Services at any time with or without cause, and with or without notice. Oweg will have no liability to Customer or any third party because of such termination.",
        "Upon termination or expiration of this Agreement by either party for any reason, (a) Oweg will cease providing the Services, (b) you will not be entitled to any refunds of any usage fees or any other fees, pro rata or otherwise and (c) any outstanding balance owed to Oweg for your usage of the Services through the effective date of such termination or expiration will immediately become due and payable in full. All sections of this Agreement which by their nature should survive termination will survive termination, including, without limitation, warranty disclaimers and limitations of liability.",
        "Upon termination or expiration of this Agreement by either party for any reason, Oweg may delete any Customer archived data within 30 days after the date of termination.",
      ],
    },
    {
      title: "4. Disputes Regarding Account or Site Ownership",
      bullets: [
        "If multiple persons are claiming ownership of or rights in a site, store or account, and, in Oweg sole judgment, there is uncertainty as to the ownership of or rights in such site, store or account, then Oweg Enterprises will, to the extent of its knowledge and ability, notify such persons of the dispute and demand that such persons promptly, conclusively, and finally resolve the dispute in a manner which makes clear who the owner(s) and/or interest holder(s) is/are and in a manner which relieves Oweg of all liability and obligations concerning the dispute and such site, store or account. If the disputing persons fail to resolve the dispute within what Oweg, in its sole judgment, deems to be a reasonable time, then Oweg , at its sole option and without any obligation to do so, may suspend or terminate the account until such persons resolve such dispute and reach certainty regarding ownership of or rights in such website, store and/or account. The person or persons conclusively and finally determined by court order, binding arbitration or settlement agreement to be the rightful owner(s) or interest holder(s) of such website, store and/or account will be obligated to pay all amounts due and comply with the then current Oweg policy regarding transfers of accounts, if required, to transfer ownership of the site, store and/or account to the rightful owner. Failure of the rightful owner of such site, store and/or account to timely pay in full all of such amounts will be deemed a breach of these Terms and will subject the account to immediate termination.",
      ],
    },
    {
      title: "5. Customer's Name and Trademarks; Customer Feedback; Customer Submissions",
      bullets: [
        "Name and Trademarks. Customer hereby grants Oweg Enterprises a non-exclusive right and license to use Customer's name and such of Customer's trade names, trademarks, and service marks (collectively, \"Customer's Marks\") as are provided to Oweg in connection with this Agreement (a) on Oweg own websites, (b) in printed and online advertising, publicity, directories, newsletters, and updates describing Oweg Services and (c) in applications reasonably necessary and ancillary to the foregoing.",
        "Customer Content. Some of the features of this website or the Services found at this website may allow Customer to view, post, publish, share, store, or manage (a) ideas, opinions, recommendations, feedback or advice (\"Customer Feedback\"), or (b) literary, artistic or other content, including but not limited to photos and videos (\"Customer Submissions\") (Customer Feedback together with Customer Submissions, \"Customer Content\"). By providing Customer Content to Oweg Enterprises via any method (e.g. site submission, email, survey responses, etc.), Customer represents and warrants to Oweg Enterprises that (i) Customer has all necessary rights to distribute Customer Content via this website or via the Services found at this website, either because Customer is the author of the Customer Content and has the right to distribute the same, or because Customer has the appropriate distribution rights, licenses and/or permissions to use, in writing, from the copyright or other owner of the Customer Content, and (ii) Customer does not violate the rights of any third party.",
        "License to Oweg . Oweg will have the right to use and disclose any Customer Content posted to Oweg corporate websites or submitted directly to Oweg for any lawful purpose. In no event will Customer or anyone else be entitled to any compensation or acknowledgement for Oweg use of any Customer Content. Customer's provision of Customer Content is entirely voluntary and will not create any confidentiality obligation for Oweg. By submitting Customer Content, Customer hereby grants Oweg an irrevocable, perpetual, transferable, non-exclusive, fully-paid-up, royalty-free, worldwide license (sublicensable through multiple tiers) to: (a) use, copy, distribute, reproduce, modify, create derivative works of, adapt, publish, translate, publicly perform, and publicly display Customer Content (or any modification thereto), in whole or in part, in any format, medium or application now known or later developed, and (b) use (and permit others to use) Customer Content in any manner and for any purpose (including, but not limited to, commercial purposes) that Oweg deems appropriate in its sole discretion (including, but not limited to, to incorporating Customer Content (or any modification thereto), in whole or in part, into any technology, product or service. The provisions in this Section apply specifically to Oweg use of Customer Content posted to Oweg corporate websites or submitted directly to Oweg . The provisions in this Section are not intended to and do not have the effect of transferring any ownership (including intellectual property rights) Customer may have in content posted to Customer's hosted sites or granting any license (including intellectual property rights) to content posted to Customer's hosted sites (other than as necessary for Oweg to host Customer's sites and provide the Services). Customer will be solely responsible for any and all of the Customer Content that is submitted through Customer's account, and the consequences of, and requirements for, distributing it.",
      ],
    },
    {
      title: "6. Export of Services or Technical Data",
      bullets: [
        "Customer may not remove or export from Australia or the United States or allow the export or re-export of the Services, or any direct product thereof, including technical data, in violation of any restrictions, laws, or regulations of Australia, the United States or any other applicable country.",
      ],
    },
    {
      title: "7. Fees and Payment; Upgrade, Downgrade and Cancellation of Services",
      bullets: [
        "Fees. In consideration of the Services provided, Customer will pay Oweg all fees due according to the prices and terms listed on this website. Oweg reserves the right to modify its pricing and terms at any time, and such changes or modifications will be posted on this website and effective immediately upon the next renewal, billing period, upgrade or downgrade of the Services with and/or without notice to Customer. All payments are NON-REFUNDABLE.",
        "Taxes. All fees are exclusive of all federal, state, and/or other governmental sales, goods and services, harmonized or other taxes, fees or charges. If Customer is a resident of Australia, Customer is responsible for all applicable Goods and Services Taxes.",
        "Billing Policies and Cycles. All billing invoices and payment notifications will be maintained directly in Customer's Account Portal. The billing cycle begins on the day Customer converts to a paid store (the \"Billing Date\") and is due on that day each month, partial year or year thereafter, depending on the Service plan selected and billing terms for individual Services. Billing related to the purchase of SSLs or Domains are billed once these products/services have been purchased by Customer.",
        "Payment. A valid credit card is required for accounts to process payment. Oweg Enterprises will automatically charge Customer's credit card on file based on Customer's billing cycle (monthly, partial yearly or yearly, depending on the Services selected and billing terms for individual Services) until Customer validly terminates the Services. Fees for prepaid Services are based on Services purchased, regardless of actual usage and payments made for such Services are NON-REFUNDABLE. Oweg Enterprises DOES NOT PROVIDE REFUNDS OR CREDITS FOR ANY PARTIAL DAYS, MONTHS OR YEARS AND DOES NOT PROVIDE REFUNDS TO CUSTOMERS WHO DO NOT USE THEIR ACCOUNTS OR LOG IN.",
        "Disputed Charges/Billing Inquiries. It is Customer's obligation to review all charges for accuracy. Customer has 30 days from the date of billing to contact Oweg Enterprises and/or dispute the charge. Failure to do so within the specified time frame will constitute Customer's agreement that all charges are valid and Customer thereby waives any claims it may have had regarding such charge.",
        "Upgrades. Should Customer elect to upgrade its prepaid Services or if such Services are automatically upgraded pursuant to the last sentence of this Section 7.7, the Billing Date of the next renewal period will remain the same; however, Customer will be billed immediately for the pro-rata portion of the upgraded Services fee for the remainder of the current billing period. For example, if a month-to-month customer is billed on October 9th for monthly prepaid Services from October 9th to November 8th, and such Customer's account is upgraded effective on October 30th, then such Customer will be charged immediately for the pro-rata usage of the upgraded plan from October 30th to November 8th. On November 9th such Customer will be charged for the full monthly fee amount of the upgraded plan.",
        "Downgrades. Should Customer elect to downgrade its prepaid Services, the downgrade will take effect on the commencement of the next renewal period. In other words, Oweg Enterprises DOES NOT provide credits or refunds on downgrades that are effective during the applicable billing period (whether such period is a month, quarter or year). For example, if a month-to-month customer is billed on October 9th for prepaid Services from October 9th to November 8th and such customer downgrades the prepaid Services effective on October 30th, then the downgrade will take effect on the next billing date, i.e. November 9th.",
        "Cancellations. Oweg Enterprises Services will continue in effect until Customer validly terminates the Services.",
        "Customer may terminate Oweg Enterprises Analytics upon request. If the termination date is after the Billing Date for the Service, Customer will be billed for Oweg Enterprises Analytics based on the applicable pricing tier using the Customer's store's order volume for the preceding 30 days from the termination date and prorated based on usage. For example, if Customer's Billing Date is the 15th of every month and Customer terminates with an effective date of termination on June 8, Customer's final bill for Oweg Enterprises Analytics will be calculated based on Customer's store's order volume for the proceeding 30 days as of the termination date and the applicable tiered pricing will be pro-rated from May 15 through June 8. If Customer terminates Oweg Enterprises Analytics prior to the first Billing Date after Customer adds the Service, Customer's final bill for Oweg Enterprises Analytics will be based on the applicable pricing tier using Customer's store's order volume for the preceding 30 days and prorated for usage.",
      ],
    },
    {
      title: "8. Prohibited Practices",
      bullets: [
        "Prohibited Offerings. Customer may not utilize the Services to provide, sell or offer to sell the following: replicas; controlled substances; illegal drugs and drug contraband; weapons; pirated materials; instructions on making, assembling or obtaining illegal goods or weapons to attack others; information used to violate the copyright(s) of, violate the trademark(s) of or to destroy others' intellectual property or information; information used to illegally harm any people or animals; pornography, nudity, sexual products, programs or services; escort services or other content deemed adult related.",
        "Profanity. Profanity, profane or otherwise inappropriate subject matter in the site content and in the domain name are prohibited.",
        "Private Information and Images. Customers may not post or disclose any personal or private information about or images of children or any third party without the consent of such party (or a parent's consent in the case of a minor).",
        "Violations of Intellectual Property Rights. Any violation of any person's or entity's intellectual property rights, rights of privacy, rights of publicity or other personal rights is prohibited. Oweg Enterprises may remove or block access to content appearing on or through the Services upon receipt of proper notice of copyright infringement (see \"Reporting Claims of Copyright Infringement\" below).",
        "Misrepresentation of Transmission Information. Forging, misrepresenting, omitting, or deleting message headers, return mailing information and/or Internet protocol addresses to conceal or misidentify the origin of a message is prohibited.",
        "Viruses and Other Destructive Activities. Use of the Services for creating or sending Internet viruses, worms or Trojan horses, or for pinging, flooding or mail bombing, or engaging in denial of service attacks is prohibited. It is also prohibited for Customer to engage in other activity that is intended to disrupt or interfere with, or that results in the disruption of or interference with, the ability of others to effectively use the Services (or any connected network, system, service or equipment) or conduct their business over the Internet.",
        "Hacking. \"Hacking\" and related activities are prohibited. \"Hacking\" includes, but is not limited to, the following activities: illegally or without authorization, accessing computers, accounts or networks, penetrating or attempting to penetrate security measures, port scans, stealth scans, and other activities designed to assist in hacking.",
        "Anonymous Proxies. Oweg Enterprises does not allow the use of anonymous proxy scripts on its servers. They can be very abusive to the server resources, affecting all users on that server. Customer will not access or copy any portion of the Services through any automated viewing, downloading or crawling systems.",
        "Export Control Violations. The exportation of encryption software outside of Australia or the United States and/or violations of Australian or United States law relating to the exportation of software is prohibited. Customer may not export or transfer, directly or indirectly, any regulated product or information to anyone outside Australia or the United States without complying with all applicable statues, codes, ordinances, regulations, and rules imposed by Australian and United States federal, state or local law, or by any other applicable law.",
        "Child Pornography. The use of the Services to store, post, display, transmit, sell, advertise or otherwise make available child pornography is prohibited. Oweg Enterprises is required by law to, and will, notify law enforcement agencies when it becomes aware of the presence of child pornography on, or being transmitted through, the Services.",
      ],
    },
    {
      title: "9. Backup Storage",
      bullets: [
        "Oweg Enterprises offers its Services to host ecommerce websites, not to store data. Using an account as an online storage space for archiving electronic files is prohibited and will result in termination of Services without prior notice. For its own operational efficiencies and purposes, Oweg Enterprises from time to time backs up data on its servers, but is under no obligation or duty to Customer to do so under these Terms. IT IS SOLELY CUSTOMER'S DUTY AND RESPONSIBILITY TO SEPARATELY BACKUP CUSTOMER'S FILES AND DATA WHICH MAY RESIDE ON Oweg Enterprises SERVERS. UNDER NO CIRCUMSTANCES WILL Oweg Enterprises BE LIABLE TO ANYONE FOR DAMAGES OF ANY KIND UNDER ANY LEGAL THEORY FOR LOSS OF CUSTOMER'S FILES AND/OR DATA ON ANY Oweg Enterprises SERVER.",
      ],
    },
    {
      title: "10. Miscellaneous",
      subsections: [
        {
          title: "Governing Law; Jurisdiction",
          paragraphs: [
            "The laws of the State of New York will govern the validity and construction of these Terms and any dispute arising out of or relating to these Terms, without regard to the principles of conflict of laws. Customer hereby consents (and waives all defenses of lack of personal jurisdiction and forum non conveniens with respect to the jurisdiction and venue of the federal and state courts located in New York (USA). Customer agrees to waive the right to trial by jury in any action or proceeding that takes place relating to or arising out of this Agreement. The United Nations Convention on Contracts for the International Sale of Goods will not apply to these Terms and is hereby expressly excluded.",
          ],
        },
        {
          title: "Warranty Disclaimer",
          paragraphs: [
            'CUSTOMER SPECIFICALLY ACKNOWLEDGES AND AGREES THAT ITS USE OF THIS WEBSITE AND THE SERVICES FOUND AT THIS WEBSITE WILL BE AT ITS OWN RISK AND THAT THIS WEBSITE AND THE SERVICES FOUND AT THIS WEBSITE ARE PROVIDED "AS IS", "AS AVAILABLE" AND "WITH ALL FAULTS". Oweg Enterprises, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS DISCLAIM ALL WARRANTIES, CONDITIONS, REPRESENTATIONS, STATUTORY, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES, CONDITIONS AND REPRESENTATIONS OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.',
            "IN ADDITION, CUSTOMER SPECIFICALLY ACKNOWLEDGES AND AGREES THAT NO ORAL OR WRITTEN INFORMATION OR ADVICE PROVIDED BY Oweg Enterprises, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS (INCLUDING WITHOUT LIMITATION ITS CALL CENTER OR CUSTOMER SERVICE REPRESENTATIVES), WHETHER DIRECTLY OR INDIRECTLY, WILL (A) CONSTITUTE PERSONAL, LEGAL OR FINANCIAL ADVICE OR (B) CREATE A WARRANTY, CONDITION OR REPRESENTATION OF ANY KIND WITH RESPECT TO THIS WEBSITE OR THE SERVICES FOUND AT THIS WEBSITE. CUSTOMER SHOULD NOT RELY ON ANY SUCH INFORMATION OR ADVICE, AND CUSTOMER SHOULD CONSULT AN APPROPRIATE PROFESSIONAL FOR SPECIFIC ADVICE TAILORED TO ITS SITUATION.",
            "THE FOREGOING DISCLAIMER OF REPRESENTATIONS, CONDITIONS AND WARRANTIES WILL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW, AND WILL SURVIVE ANY TERMINATION OR EXPIRATION OF THIS AGREEMENT OR CUSTOMER'S USE OF THIS WEBSITE OR THE SERVICES FOUND AT THIS WEBSITE.",
            "SOME JURISDICTIONS MAY NOT ALLOW THE EXCLUSION AND/OR LIMITATION OF IMPLIED REPRESENTATIONS, CONDITIONS OR WARRANTIES, OR ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO CUSTOMER. IN SUCH EVENT, Oweg Enterprises'S WARRANTIES, CONDITIONS AND REPRESENTATIONS WITH RESPECT TO THIS WEBSITE, THE SERVICES, AND SOFTWARE WILL BE LIMITED TO THE GREATEST EXTENT PERMITTED BY APPLICABLE LAW IN SUCH JURISDICTION.",
          ],
        },
        {
          title: "Limitation of Liability",
          paragraphs: [
            "Oweg Enterprises, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS ASSUME NO RESPONSIBILITY WITH RESPECT TO CUSTOMER'S OR ITS END USER'S USE OF THE SERVICES AND WILL NOT BE LIABLE FOR CONSEQUENTIAL, INDIRECT, INCIDENTAL, PUNITIVE, EXTRAORDINARY, EXEMPLARY OR SPECIAL DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF USE, BUSINESS INTERRUPTIONS, LOSS OF DATA, LOSS OF PROFITS, AND LOST REVENUE, WHETHER SUCH DAMAGES ARE ALLEGED IN TORT, CONTRACT OR ANY OTHER LEGAL OR EQUITABLE THEORY, AND WHETHER OR NOT Oweg Enterprises IS AWARE OF THE POSSIBILITY OF SUCH DAMAGES. Oweg Enterprises, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS WILL IN NO EVENT BE LIABLE IN AGGREGATE FOR MORE THAN THE TOTAL FEES ACTUALLY RECEIVED BY Oweg Enterprises FROM CUSTOMER FOR THE SERVICES DURING THE 12-MONTH PERIOD BEFORE THE CLAIM OR CAUSE OF ACTION AROSE. MULTIPLE CLAIMS WILL NOT EXPAND THIS LIMITATION.",
            "IN ADDITION, YOU SPECIFICALLY ACKNOWLEDGE AND AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THIS WEBSITE OR THE SERVICES FOUND AT THIS WEBSITE MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES, OTHERWISE SUCH CAUSE OF ACTION WILL BE PERMANENTLY BARRED.",
            "SOME JURISDICTIONS MAY NOT ALLOW THE EXCLUSION OR LIMITATION OF CONSEQUENTIAL, INCIDENTAL, SPECIAL OR OTHER DAMAGES, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO CUSTOMER. IN SUCH EVENT, THE LIABILITY OF Oweg Enterprises, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS FOR SUCH DAMAGES WITH RESPECT TO THIS WEBSITE AND THE SERVICES WILL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW, AND WILL SURVIVE ANY TERMINATION OR EXPIRATION OF THIS AGREEMENT OR CUSTOMER'S USE OF THIS WEBSITE OR THE SERVICES FOUND AT THIS WEBSITE.",
          ],
        },
        {
          title: "Indemnification of Oweg Enterprises",
          paragraphs: [
            "Customer agrees to defend, indemnify and hold Oweg Enterprises and its Content Providers and the respective directors, officers, employees and agents of each harmless from and against any and all claims, losses, damages, liabilities and costs (including, without limitation, reasonable attorneys' fees and court costs) arising out of or relating to Customer's breach of any of these Terms or use by Customer or any third party (authorized, permitted or enabled by Customer) of the Services, except to the extent the foregoing directly result from Oweg Enterprises's own gross negligence or willful misconduct. Oweg Enterprises reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by Customer. THIS FOREGOING INDEMNIFICATION WILL SURVIVE ANY TERMINATION OR EXPIRATION OF THIS AGREEMENT OR CUSTOMER'S USE OF THIS WEBSITE OR THE SERVICES FOUND AT THIS WEBSITE.",
          ],
        },
        {
          bullets: [
            "Severability. If any provision of this Agreement is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that this Agreement will otherwise remain in full force and effect and enforceable.",
            "No Assignment by Customer. Customer may not assign this Agreement without the prior written consent of Oweg Enterprises, which Oweg Enterprises may refuse in its sole discretion. Any attempt by Customer to assign this Agreement without prior written consent from Oweg Enterprises will be deemed null and void. Oweg Enterprises may assign this Agreement at any time. Subject to the foregoing, this Agreement will bind and inure to the benefit of the parties, their respective successors and permitted assigns.",
            "Waiver. The failure of Oweg Enterprises to exercise or enforce any right or provision of these Terms or this Agreement will not constitute a waiver of such right or provision.",
            "Entire Agreement. Both parties agree that this Agreement is the complete and exclusive statement of the mutual understanding of the parties and supersedes and cancels all previous written and oral agreements, communications, and other understandings relating to the subject matter of this Agreement, and that all waivers and modifications must be in a writing signed by both parties, except as otherwise provided herein. The section headings and titles in these Terms and this Agreement are for convenience only and have no legal or contractual effect. These Terms and this Agreement will be interpreted without application of any strict construction in favor of or against Customer or Oweg Enterprises.",
            "Independent Contractors. No agency, partnership, joint venture or employment is created as a result of this Agreement, and Customer does not have any authority of any kind to bind Oweg Enterprises in any respect whatsoever.",
            "Attorneys' Fees. In any action or proceeding to enforce rights under this Agreement, the prevailing party will be entitled to recover its costs and attorneys' fees.",
            "Force Majeure. Oweg Enterprises will have no liability to Customer or any third party for any failure by Oweg Enterprises to perform its obligations under these Terms in the event that such non-performance arises as a result of the occurrence of an event beyond the reasonable control of Oweg Enterprises, including without limitation an act of war or terrorism, natural disaster, failure of electricity supply, riot, civil disorder, or civil commotion or other event of force majeure.",
          ],
        },
      ],
    },
    {
      title: "11. Additional Service Specific Terms",
      paragraphs: [
        "In addition to the Terms above, Customer also agrees to be bound by the additional service specific terms applicable to the Services Customer purchases or uses provided by Oweg Enterprises or its partners. The following Service Specific Terms are hereby incorporated by reference and are binding upon Customer.",
      ],
      subsections: [
        {
          title: "Third Party Services, Websites, Links and Information",
          paragraphs: [
            "Oweg Enterprises or its personnel may from time to time recommend or enable third party software, products, services or website links for Customer's consideration or use. Such software, products, services, and links are provided only as a convenience to customers of the Services. Some of the Services made available through this website may be subject to additional third party licensing terms or third party terms of use, including the ones posted here and incorporated herein by reference. Inclusion of any of the foregoing in the Services does not constitute or imply an endorsement, authorization, sponsorship, or affiliation by or with Oweg Enterprises with respect to any third party, any third party's website or its content, or any information, products, or services provided by a third party.",
            "These Terms and the Privacy Policy do not apply to such third party websites, and Customer should review such third party websites' privacy policies, terms and conditions and business practices as they may be different than Oweg Terms and it is Customer's sole responsibility to comply with such third party terms. Access to any other website is at Customer's own risk, and Customer's dealings and communications with any third party in connection with such third party's website are solely between Customer and such third party.",
            "OWEG MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING THIRD PARTY SOFTWARE, PRODUCTS OR SERVICES AND WILL NOT BE LIABLE FOR ANY SOFTWARE, PRODUCTS OR SERVICES CUSTOMER RECEIVES FROM THIRD PARTIES.",
          ],
        },
        {
          title: "Oweg Enterprises Theme Store",
          bullets: [
            "Except as otherwise expressly provided at checkout when licensing a Design Theme, refunds will not be issued to Customers for Design Themes once they are installed on the Customer's store.",
            "All Design Themes are licensed under a non-exclusive license agreement and can be reproduced and redistributed an unlimited number of times by Oweg Enterprises.",
            "Oweg Enterprises grants to Customer, for so long as Customer continues to subscribe and pay for the Services, a nonexclusive license to modify, make derivative works of and use, each licensed Design Theme solely in conjunction with the Oweg Enterprises platform and the Services. For clarity, the foregoing license only allows Customer to use each licensed Design Theme for a single Oweg Enterprises store/website per license purchased. If Customer desires to use a Design Theme for more than one Oweg Enterprises store owned or operated by Customer, a new Design Theme license must be purchased for each such store using the Design Theme. Design Themes may only be used by a Customer and may not be transferred by Customer to any unaffiliated third party without the prior written consent of Oweg Enterprises. For clarity, Customer may not license, sublicense, assign, transfer, redistribute or sell any Design Themes or derivative works thereof to any other parties. The Design Theme is the exclusive property of our design partner, and all right, title and interest in each Design Theme shall remain exclusively with the applicable design partner.",
            "If Customer licenses a Design Theme for its website, Oweg Enterprises may provide your personal information to our design partner to facilitate the design partner's provision and/or offer of support/services and/or products to the Customer.",
            "If Customer customizes a Design Theme, neither Oweg Enterprises nor its design partners are obligated to support that Design Theme.",
          ],
        },
        {
          title: "Migration and Store Set Up Services",
          bullets: [
            "Oweg Enterprises offers migration services (\"Migration Services\") to Customers purchasing select Service plans as described on our website. Oweg Enterprises supports most standard shopping cart database schemes by default. Our Migration Services do not guarantee proper migration of the custom data, fields or information handled by third-party modules and/or contributions.",
            "If you transfer data to a live store, it is highly recommended that you turn on \"maintenance mode\" or a similar setting on your target shopping cart before migration. This action will help to avoid the possible loss of orders placed during the migration procedure. You can find the information on how to turn on maintenance mode in documentation for your shopping cart.",
            "The Store Set Up Service includes configuration of basic Oweg Enterprises store settings and is available with select plans or for an additional fee.",
            "If Customer selects the Enterprise Service plan and chooses to cancel or downgrade to any lesser plan within six months following the commencement of Customer's Service for such plan (i.e., six months from the date on which Customer originally registers for such plan), Customer will be responsible for an early termination fee of $325 to cover costs associated with migration and set up.",
            "Migration Services and Store Set Up Services are Services for which we charge a one-time, upfront fee. All such Services are non-refundable, except solely at the discretion of Oweg Enterprises in the case of a major technical issue that is exclusively the fault of Oweg Enterprises and that Oweg Enterprises is unable to resolve within 72 hours of receipt of written notification. In the event Oweg Enterprises determines, in its sole and complete discretion, to refund Customer's prepayment for Migration Services, then Customer covenants and agrees to delete all migrated data, including images, MySQL dumps, CSV/XML files and/or backups containing these files.",
          ],
        },
      ],
    },
  ],
};
