"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const utils_1 = require("@medusajs/framework/utils");
const affiliate_admin_1 = __importDefault(require("./models/affiliate-admin"));
const affiliate_user_1 = __importDefault(require("./models/affiliate-user"));
const affiliate_commission_1 = __importDefault(require("./models/affiliate-commission"));
const bcryptjs_1 = __importDefault(require("bcryptjs"));
class AffiliateModuleService extends (0, utils_1.MedusaService)({
    AffiliateAdmin: affiliate_admin_1.default,
    AffiliateUser: affiliate_user_1.default,
    AffiliateCommission: affiliate_commission_1.default,
}) {
    async createAffiliateAdmin(input) {
        // Check for duplicate email
        const existing = await this.listAffiliateAdmins({ email: input.email });
        if (existing && existing.length > 0) {
            throw new utils_1.MedusaError(utils_1.MedusaError.Types.DUPLICATE_ERROR, "Affiliate admin with email already exists");
        }
        // Hash password
        const password_hash = await bcryptjs_1.default.hash(input.password, 10);
        // Create affiliate admin
        return await this.createAffiliateAdmins({
            name: input.name,
            email: input.email,
            password_hash,
        });
    }
    async authenticateAffiliateAdmin(email, password, ip) {
        const admins = await this.listAffiliateAdmins({ email });
        if (!admins || admins.length === 0) {
            throw new utils_1.MedusaError(utils_1.MedusaError.Types.UNAUTHORIZED, "Invalid credentials");
        }
        const admin = admins[0];
        const ok = await bcryptjs_1.default.compare(password, admin.password_hash);
        if (!ok) {
            throw new utils_1.MedusaError(utils_1.MedusaError.Types.UNAUTHORIZED, "Invalid credentials");
        }
        // Update last login time and IP
        await this.updateAffiliateAdmins({
            id: admin.id,
            last_login_at: new Date(),
            login_ip: ip || null,
        });
        return admin;
    }
    async updateAffiliateAdminLogin(adminId, ip) {
        await this.updateAffiliateAdmins({
            id: adminId,
            last_login_at: new Date(),
            login_ip: ip || null,
        });
    }
    // Affiliate User methods
    async createAffiliateUser(input) {
        // Check for duplicate email in both admin and user tables
        const existingAdmin = await this.listAffiliateAdmins({ email: input.email });
        const existingUser = await this.listAffiliateUsers({ email: input.email });
        if ((existingAdmin && existingAdmin.length > 0) || (existingUser && existingUser.length > 0)) {
            throw new utils_1.MedusaError(utils_1.MedusaError.Types.DUPLICATE_ERROR, "Email already exists");
        }
        // Hash password
        const password_hash = await bcryptjs_1.default.hash(input.password, 10);
        // Generate unique referral code: OWEG{USERNAME}{5DIGITRANDOM}
        const generateReferralCode = async () => {
            // Extract username from first_name, remove non-letters, uppercase, max 10 chars
            let username = input.first_name.toUpperCase().replace(/[^A-Z]/g, '');
            if (username.length === 0) {
                username = "USER";
            }
            else if (username.length > 10) {
                username = username.substring(0, 10);
            }
            let attempts = 0;
            const maxAttempts = 10;
            while (attempts < maxAttempts) {
                // Generate 5 random digits (10000-99999)
                const randomDigits = Math.floor(10000 + Math.random() * 90000).toString();
                const referralCode = `OWEG${username}${randomDigits}`;
                // Check if code already exists
                const existingUsers = await this.listAffiliateUsers({ refer_code: referralCode });
                // Check if any admin has this refer_code (if we add it to admin model later)
                const existingAdmins = await this.listAffiliateAdmins({});
                const codeExists = (existingUsers && existingUsers.length > 0) ||
                    (existingAdmins && existingAdmins.some((a) => a.refer_code === referralCode));
                if (!codeExists) {
                    return referralCode;
                }
                attempts++;
            }
            // Fallback: use timestamp if all attempts fail
            const timestamp = Date.now().toString().slice(-5);
            return `OWEG${username}${timestamp}`;
        };
        const autoGeneratedReferCode = await generateReferralCode();
        // Parse birth_date if provided
        let birthDate = null;
        if (input.birth_date) {
            // Handle dd-mm-yyyy format
            const parts = input.birth_date.split('-');
            if (parts.length === 3) {
                const day = parseInt(parts[0], 10);
                const month = parseInt(parts[1], 10) - 1; // Month is 0-indexed
                const year = parseInt(parts[2], 10);
                birthDate = new Date(year, month, day);
            }
            else {
                birthDate = new Date(input.birth_date);
            }
        }
        // Create affiliate user (pending approval by default)
        // Note: input.refer_code is the referral code they entered (entry_sponsor)
        // autoGeneratedReferCode is their own unique referral code
        return await this.createAffiliateUsers({
            first_name: input.first_name,
            last_name: input.last_name,
            email: input.email,
            password_hash,
            phone: input.phone || null,
            refer_code: autoGeneratedReferCode, // Auto-generated unique code for this user
            entry_sponsor: input.entry_sponsor || input.refer_code || null, // The referral code they entered (their sponsor's code)
            is_agent: input.is_agent || false,
            is_approved: false,
            gender: input.gender || null,
            father_name: input.father_name || null,
            mother_name: input.mother_name || null,
            birth_date: birthDate,
            qualification: input.qualification || null,
            marital_status: input.marital_status || null,
            blood_group: input.blood_group || null,
            emergency_person_name: input.emergency_person_name || null,
            emergency_person_mobile: input.emergency_person_mobile || null,
            aadhar_card_no: input.aadhar_card_no || null,
            pan_card_no: input.pan_card_no || null,
            aadhar_card_photo: input.aadhar_card_photo || null,
            pan_card_photo: input.pan_card_photo || null,
            designation: input.designation || null,
            sales_target: input.sales_target || null,
            branch: input.branch || null,
            area: input.area || null,
            state: input.state || null,
            payment_method: input.payment_method || null,
            bank_name: input.bank_name || null,
            bank_branch: input.bank_branch || null,
            ifsc_code: input.ifsc_code || null,
            account_name: input.account_name || null,
            account_number: input.account_number || null,
            address_1: input.address_1 || null,
            address_2: input.address_2 || null,
            city: input.city || null,
            pin_code: input.pin_code || null,
            country: input.country || null,
            address_state: input.address_state || null,
        });
    }
    async authenticateAffiliateUser(email, password, ip) {
        // Try to authenticate as admin first
        const admins = await this.listAffiliateAdmins({ email });
        if (admins && admins.length > 0) {
            const admin = admins[0];
            const ok = await bcryptjs_1.default.compare(password, admin.password_hash);
            if (ok) {
                // Update last login time and IP
                await this.updateAffiliateAdmins({
                    id: admin.id,
                    last_login_at: new Date(),
                    login_ip: ip || null,
                });
                return { ...admin, role: "admin" };
            }
        }
        // Try to authenticate as regular user
        const users = await this.listAffiliateUsers({ email });
        if (!users || users.length === 0) {
            throw new utils_1.MedusaError(utils_1.MedusaError.Types.UNAUTHORIZED, "Invalid credentials");
        }
        const user = users[0];
        const ok = await bcryptjs_1.default.compare(password, user.password_hash);
        if (!ok) {
            throw new utils_1.MedusaError(utils_1.MedusaError.Types.UNAUTHORIZED, "Invalid credentials");
        }
        // Update last login time and IP
        await this.updateAffiliateUsers({
            id: user.id,
            last_login_at: new Date(),
            login_ip: ip || null,
        });
        return { ...user, role: "user" };
    }
    async approveAffiliateUser(userId, adminId) {
        const users = await this.listAffiliateUsers({ id: userId });
        if (!users || users.length === 0) {
            throw new utils_1.MedusaError(utils_1.MedusaError.Types.NOT_FOUND, `Affiliate user with id "${userId}" not found`);
        }
        const user = users[0];
        if (user.is_approved) {
            return user;
        }
        const updated = await this.updateAffiliateUsers({
            id: userId,
            is_approved: true,
            approved_at: new Date(),
            approved_by: adminId || null,
            rejected_at: null,
            rejected_by: null,
            rejection_reason: null,
        });
        return updated;
    }
    async rejectAffiliateUser(userId, rejectionReason, adminId) {
        const users = await this.listAffiliateUsers({ id: userId });
        if (!users || users.length === 0) {
            throw new utils_1.MedusaError(utils_1.MedusaError.Types.NOT_FOUND, `Affiliate user with id "${userId}" not found`);
        }
        const updated = await this.updateAffiliateUsers({
            id: userId,
            is_approved: false,
            rejection_reason: rejectionReason,
            rejected_at: new Date(),
            rejected_by: adminId || null,
        });
        return updated;
    }
    // Commission methods
    async createCommission(input) {
        // Validate that exactly one of product_id, category_id, collection_id, or type_id is set
        const ids = [input.product_id, input.category_id, input.collection_id, input.type_id].filter(Boolean);
        if (ids.length !== 1) {
            throw new utils_1.MedusaError(utils_1.MedusaError.Types.INVALID_DATA, "Exactly one of product_id, category_id, collection_id, or type_id must be provided");
        }
        // Validate commission_rate is between 0 and 100
        if (input.commission_rate < 0 || input.commission_rate > 100) {
            throw new utils_1.MedusaError(utils_1.MedusaError.Types.INVALID_DATA, "Commission rate must be between 0 and 100");
        }
        // Check if commission already exists for this entity
        const existing = await this.listAffiliateCommissions({
            product_id: input.product_id || undefined,
            category_id: input.category_id || undefined,
            collection_id: input.collection_id || undefined,
            type_id: input.type_id || undefined,
        });
        if (existing && existing.length > 0) {
            // Update existing commission instead of creating duplicate
            const existingCommission = existing[0];
            return await this.updateAffiliateCommissions({
                id: existingCommission.id,
                commission_rate: input.commission_rate,
                metadata: input.metadata || existingCommission.metadata,
            });
        }
        return await this.createAffiliateCommissions({
            product_id: input.product_id || null,
            category_id: input.category_id || null,
            collection_id: input.collection_id || null,
            type_id: input.type_id || null,
            commission_rate: input.commission_rate,
            metadata: input.metadata || null,
        });
    }
    async updateCommission(commissionId, input) {
        const commissions = await this.listAffiliateCommissions({ id: commissionId });
        if (!commissions || commissions.length === 0) {
            throw new utils_1.MedusaError(utils_1.MedusaError.Types.NOT_FOUND, `Commission with id "${commissionId}" not found`);
        }
        // Validate commission_rate if provided
        if (input.commission_rate !== undefined) {
            if (input.commission_rate < 0 || input.commission_rate > 100) {
                throw new utils_1.MedusaError(utils_1.MedusaError.Types.INVALID_DATA, "Commission rate must be between 0 and 100");
            }
        }
        return await this.updateAffiliateCommissions({
            id: commissionId,
            commission_rate: input.commission_rate,
            metadata: input.metadata,
        });
    }
    async deleteCommission(commissionId) {
        const commissions = await this.listAffiliateCommissions({ id: commissionId });
        if (!commissions || commissions.length === 0) {
            throw new utils_1.MedusaError(utils_1.MedusaError.Types.NOT_FOUND, `Commission with id "${commissionId}" not found`);
        }
        await this.deleteAffiliateCommissions(commissionId);
        return { success: true };
    }
}
exports.default = AffiliateModuleService;
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2VydmljZS5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIi4uLy4uLy4uLy4uLy4uL3NyYy9tb2R1bGVzL2FmZmlsaWF0ZS9zZXJ2aWNlLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7O0FBQUEscURBQXNFO0FBQ3RFLCtFQUFxRDtBQUNyRCw2RUFBbUQ7QUFDbkQseUZBQStEO0FBQy9ELHdEQUE2QjtBQUU3QixNQUFNLHNCQUF1QixTQUFRLElBQUEscUJBQWEsRUFBQztJQUNqRCxjQUFjLEVBQWQseUJBQWM7SUFDZCxhQUFhLEVBQWIsd0JBQWE7SUFDYixtQkFBbUIsRUFBbkIsOEJBQW1CO0NBQ3BCLENBQUM7SUFDQSxLQUFLLENBQUMsb0JBQW9CLENBQUMsS0FJMUI7UUFDQyw0QkFBNEI7UUFDNUIsTUFBTSxRQUFRLEdBQUcsTUFBTSxJQUFJLENBQUMsbUJBQW1CLENBQUMsRUFBRSxLQUFLLEVBQUUsS0FBSyxDQUFDLEtBQUssRUFBRSxDQUFDLENBQUE7UUFDdkUsSUFBSSxRQUFRLElBQUksUUFBUSxDQUFDLE1BQU0sR0FBRyxDQUFDLEVBQUUsQ0FBQztZQUNwQyxNQUFNLElBQUksbUJBQVcsQ0FBQyxtQkFBVyxDQUFDLEtBQUssQ0FBQyxlQUFlLEVBQUUsMkNBQTJDLENBQUMsQ0FBQTtRQUN2RyxDQUFDO1FBRUQsZ0JBQWdCO1FBQ2hCLE1BQU0sYUFBYSxHQUFHLE1BQU0sa0JBQU0sQ0FBQyxJQUFJLENBQUMsS0FBSyxDQUFDLFFBQVEsRUFBRSxFQUFFLENBQUMsQ0FBQTtRQUUzRCx5QkFBeUI7UUFDekIsT0FBTyxNQUFNLElBQUksQ0FBQyxxQkFBcUIsQ0FBQztZQUN0QyxJQUFJLEVBQUUsS0FBSyxDQUFDLElBQUk7WUFDaEIsS0FBSyxFQUFFLEtBQUssQ0FBQyxLQUFLO1lBQ2xCLGFBQWE7U0FDZCxDQUFDLENBQUE7SUFDSixDQUFDO0lBRUQsS0FBSyxDQUFDLDBCQUEwQixDQUFDLEtBQWEsRUFBRSxRQUFnQixFQUFFLEVBQVc7UUFDM0UsTUFBTSxNQUFNLEdBQUcsTUFBTSxJQUFJLENBQUMsbUJBQW1CLENBQUMsRUFBRSxLQUFLLEVBQUUsQ0FBQyxDQUFBO1FBQ3hELElBQUksQ0FBQyxNQUFNLElBQUksTUFBTSxDQUFDLE1BQU0sS0FBSyxDQUFDLEVBQUUsQ0FBQztZQUNuQyxNQUFNLElBQUksbUJBQVcsQ0FBQyxtQkFBVyxDQUFDLEtBQUssQ0FBQyxZQUFZLEVBQUUscUJBQXFCLENBQUMsQ0FBQTtRQUM5RSxDQUFDO1FBRUQsTUFBTSxLQUFLLEdBQUcsTUFBTSxDQUFDLENBQUMsQ0FBQyxDQUFBO1FBQ3ZCLE1BQU0sRUFBRSxHQUFHLE1BQU0sa0JBQU0sQ0FBQyxPQUFPLENBQUMsUUFBUSxFQUFFLEtBQUssQ0FBQyxhQUFhLENBQUMsQ0FBQTtRQUM5RCxJQUFJLENBQUMsRUFBRSxFQUFFLENBQUM7WUFDUixNQUFNLElBQUksbUJBQVcsQ0FBQyxtQkFBVyxDQUFDLEtBQUssQ0FBQyxZQUFZLEVBQUUscUJBQXFCLENBQUMsQ0FBQTtRQUM5RSxDQUFDO1FBRUQsZ0NBQWdDO1FBQ2hDLE1BQU0sSUFBSSxDQUFDLHFCQUFxQixDQUFDO1lBQy9CLEVBQUUsRUFBRSxLQUFLLENBQUMsRUFBRTtZQUNaLGFBQWEsRUFBRSxJQUFJLElBQUksRUFBRTtZQUN6QixRQUFRLEVBQUUsRUFBRSxJQUFJLElBQUk7U0FDckIsQ0FBQyxDQUFBO1FBRUYsT0FBTyxLQUFLLENBQUE7SUFDZCxDQUFDO0lBRUQsS0FBSyxDQUFDLHlCQUF5QixDQUFDLE9BQWUsRUFBRSxFQUFXO1FBQzFELE1BQU0sSUFBSSxDQUFDLHFCQUFxQixDQUFDO1lBQy9CLEVBQUUsRUFBRSxPQUFPO1lBQ1gsYUFBYSxFQUFFLElBQUksSUFBSSxFQUFFO1lBQ3pCLFFBQVEsRUFBRSxFQUFFLElBQUksSUFBSTtTQUNyQixDQUFDLENBQUE7SUFDSixDQUFDO0lBRUQseUJBQXlCO0lBQ3pCLEtBQUssQ0FBQyxtQkFBbUIsQ0FBQyxLQXVDekI7UUFDQywwREFBMEQ7UUFDMUQsTUFBTSxhQUFhLEdBQUcsTUFBTSxJQUFJLENBQUMsbUJBQW1CLENBQUMsRUFBRSxLQUFLLEVBQUUsS0FBSyxDQUFDLEtBQUssRUFBRSxDQUFDLENBQUE7UUFDNUUsTUFBTSxZQUFZLEdBQUcsTUFBTSxJQUFJLENBQUMsa0JBQWtCLENBQUMsRUFBRSxLQUFLLEVBQUUsS0FBSyxDQUFDLEtBQUssRUFBRSxDQUFDLENBQUE7UUFFMUUsSUFBSSxDQUFDLGFBQWEsSUFBSSxhQUFhLENBQUMsTUFBTSxHQUFHLENBQUMsQ0FBQyxJQUFJLENBQUMsWUFBWSxJQUFJLFlBQVksQ0FBQyxNQUFNLEdBQUcsQ0FBQyxDQUFDLEVBQUUsQ0FBQztZQUM3RixNQUFNLElBQUksbUJBQVcsQ0FBQyxtQkFBVyxDQUFDLEtBQUssQ0FBQyxlQUFlLEVBQUUsc0JBQXNCLENBQUMsQ0FBQTtRQUNsRixDQUFDO1FBRUQsZ0JBQWdCO1FBQ2hCLE1BQU0sYUFBYSxHQUFHLE1BQU0sa0JBQU0sQ0FBQyxJQUFJLENBQUMsS0FBSyxDQUFDLFFBQVEsRUFBRSxFQUFFLENBQUMsQ0FBQTtRQUUzRCw4REFBOEQ7UUFDOUQsTUFBTSxvQkFBb0IsR0FBRyxLQUFLLElBQXFCLEVBQUU7WUFDdkQsZ0ZBQWdGO1lBQ2hGLElBQUksUUFBUSxHQUFHLEtBQUssQ0FBQyxVQUFVLENBQUMsV0FBVyxFQUFFLENBQUMsT0FBTyxDQUFDLFNBQVMsRUFBRSxFQUFFLENBQUMsQ0FBQTtZQUNwRSxJQUFJLFFBQVEsQ0FBQyxNQUFNLEtBQUssQ0FBQyxFQUFFLENBQUM7Z0JBQzFCLFFBQVEsR0FBRyxNQUFNLENBQUE7WUFDbkIsQ0FBQztpQkFBTSxJQUFJLFFBQVEsQ0FBQyxNQUFNLEdBQUcsRUFBRSxFQUFFLENBQUM7Z0JBQ2hDLFFBQVEsR0FBRyxRQUFRLENBQUMsU0FBUyxDQUFDLENBQUMsRUFBRSxFQUFFLENBQUMsQ0FBQTtZQUN0QyxDQUFDO1lBRUQsSUFBSSxRQUFRLEdBQUcsQ0FBQyxDQUFBO1lBQ2hCLE1BQU0sV0FBVyxHQUFHLEVBQUUsQ0FBQTtZQUV0QixPQUFPLFFBQVEsR0FBRyxXQUFXLEVBQUUsQ0FBQztnQkFDOUIseUNBQXlDO2dCQUN6QyxNQUFNLFlBQVksR0FBRyxJQUFJLENBQUMsS0FBSyxDQUFDLEtBQUssR0FBRyxJQUFJLENBQUMsTUFBTSxFQUFFLEdBQUcsS0FBSyxDQUFDLENBQUMsUUFBUSxFQUFFLENBQUE7Z0JBQ3pFLE1BQU0sWUFBWSxHQUFHLE9BQU8sUUFBUSxHQUFHLFlBQVksRUFBRSxDQUFBO2dCQUVyRCwrQkFBK0I7Z0JBQy9CLE1BQU0sYUFBYSxHQUFHLE1BQU0sSUFBSSxDQUFDLGtCQUFrQixDQUFDLEVBQUUsVUFBVSxFQUFFLFlBQVksRUFBRSxDQUFDLENBQUE7Z0JBRWpGLDZFQUE2RTtnQkFDN0UsTUFBTSxjQUFjLEdBQUcsTUFBTSxJQUFJLENBQUMsbUJBQW1CLENBQUMsRUFBRSxDQUFDLENBQUE7Z0JBQ3pELE1BQU0sVUFBVSxHQUFHLENBQUMsYUFBYSxJQUFJLGFBQWEsQ0FBQyxNQUFNLEdBQUcsQ0FBQyxDQUFDO29CQUM1QyxDQUFDLGNBQWMsSUFBSSxjQUFjLENBQUMsSUFBSSxDQUFDLENBQUMsQ0FBTSxFQUFFLEVBQUUsQ0FBQyxDQUFDLENBQUMsVUFBVSxLQUFLLFlBQVksQ0FBQyxDQUFDLENBQUE7Z0JBRXBHLElBQUksQ0FBQyxVQUFVLEVBQUUsQ0FBQztvQkFDaEIsT0FBTyxZQUFZLENBQUE7Z0JBQ3JCLENBQUM7Z0JBRUQsUUFBUSxFQUFFLENBQUE7WUFDWixDQUFDO1lBRUQsK0NBQStDO1lBQy9DLE1BQU0sU0FBUyxHQUFHLElBQUksQ0FBQyxHQUFHLEVBQUUsQ0FBQyxRQUFRLEVBQUUsQ0FBQyxLQUFLLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQTtZQUNqRCxPQUFPLE9BQU8sUUFBUSxHQUFHLFNBQVMsRUFBRSxDQUFBO1FBQ3RDLENBQUMsQ0FBQTtRQUVELE1BQU0sc0JBQXNCLEdBQUcsTUFBTSxvQkFBb0IsRUFBRSxDQUFBO1FBRTNELCtCQUErQjtRQUMvQixJQUFJLFNBQVMsR0FBZ0IsSUFBSSxDQUFBO1FBQ2pDLElBQUksS0FBSyxDQUFDLFVBQVUsRUFBRSxDQUFDO1lBQ3JCLDJCQUEyQjtZQUMzQixNQUFNLEtBQUssR0FBRyxLQUFLLENBQUMsVUFBVSxDQUFDLEtBQUssQ0FBQyxHQUFHLENBQUMsQ0FBQTtZQUN6QyxJQUFJLEtBQUssQ0FBQyxNQUFNLEtBQUssQ0FBQyxFQUFFLENBQUM7Z0JBQ3ZCLE1BQU0sR0FBRyxHQUFHLFFBQVEsQ0FBQyxLQUFLLENBQUMsQ0FBQyxDQUFDLEVBQUUsRUFBRSxDQUFDLENBQUE7Z0JBQ2xDLE1BQU0sS0FBSyxHQUFHLFFBQVEsQ0FBQyxLQUFLLENBQUMsQ0FBQyxDQUFDLEVBQUUsRUFBRSxDQUFDLEdBQUcsQ0FBQyxDQUFBLENBQUMscUJBQXFCO2dCQUM5RCxNQUFNLElBQUksR0FBRyxRQUFRLENBQUMsS0FBSyxDQUFDLENBQUMsQ0FBQyxFQUFFLEVBQUUsQ0FBQyxDQUFBO2dCQUNuQyxTQUFTLEdBQUcsSUFBSSxJQUFJLENBQUMsSUFBSSxFQUFFLEtBQUssRUFBRSxHQUFHLENBQUMsQ0FBQTtZQUN4QyxDQUFDO2lCQUFNLENBQUM7Z0JBQ04sU0FBUyxHQUFHLElBQUksSUFBSSxDQUFDLEtBQUssQ0FBQyxVQUFVLENBQUMsQ0FBQTtZQUN4QyxDQUFDO1FBQ0gsQ0FBQztRQUVELHNEQUFzRDtRQUN0RCwyRUFBMkU7UUFDM0UsMkRBQTJEO1FBQzNELE9BQU8sTUFBTSxJQUFJLENBQUMsb0JBQW9CLENBQUM7WUFDckMsVUFBVSxFQUFFLEtBQUssQ0FBQyxVQUFVO1lBQzVCLFNBQVMsRUFBRSxLQUFLLENBQUMsU0FBUztZQUMxQixLQUFLLEVBQUUsS0FBSyxDQUFDLEtBQUs7WUFDbEIsYUFBYTtZQUNiLEtBQUssRUFBRSxLQUFLLENBQUMsS0FBSyxJQUFJLElBQUk7WUFDMUIsVUFBVSxFQUFFLHNCQUFzQixFQUFFLDJDQUEyQztZQUMvRSxhQUFhLEVBQUUsS0FBSyxDQUFDLGFBQWEsSUFBSSxLQUFLLENBQUMsVUFBVSxJQUFJLElBQUksRUFBRSx3REFBd0Q7WUFDeEgsUUFBUSxFQUFFLEtBQUssQ0FBQyxRQUFRLElBQUksS0FBSztZQUNqQyxXQUFXLEVBQUUsS0FBSztZQUNsQixNQUFNLEVBQUUsS0FBSyxDQUFDLE1BQU0sSUFBSSxJQUFJO1lBQzVCLFdBQVcsRUFBRSxLQUFLLENBQUMsV0FBVyxJQUFJLElBQUk7WUFDdEMsV0FBVyxFQUFFLEtBQUssQ0FBQyxXQUFXLElBQUksSUFBSTtZQUN0QyxVQUFVLEVBQUUsU0FBUztZQUNyQixhQUFhLEVBQUUsS0FBSyxDQUFDLGFBQWEsSUFBSSxJQUFJO1lBQzFDLGNBQWMsRUFBRSxLQUFLLENBQUMsY0FBYyxJQUFJLElBQUk7WUFDNUMsV0FBVyxFQUFFLEtBQUssQ0FBQyxXQUFXLElBQUksSUFBSTtZQUN0QyxxQkFBcUIsRUFBRSxLQUFLLENBQUMscUJBQXFCLElBQUksSUFBSTtZQUMxRCx1QkFBdUIsRUFBRSxLQUFLLENBQUMsdUJBQXVCLElBQUksSUFBSTtZQUM5RCxjQUFjLEVBQUUsS0FBSyxDQUFDLGNBQWMsSUFBSSxJQUFJO1lBQzVDLFdBQVcsRUFBRSxLQUFLLENBQUMsV0FBVyxJQUFJLElBQUk7WUFDdEMsaUJBQWlCLEVBQUUsS0FBSyxDQUFDLGlCQUFpQixJQUFJLElBQUk7WUFDbEQsY0FBYyxFQUFFLEtBQUssQ0FBQyxjQUFjLElBQUksSUFBSTtZQUM1QyxXQUFXLEVBQUUsS0FBSyxDQUFDLFdBQVcsSUFBSSxJQUFJO1lBQ3RDLFlBQVksRUFBRSxLQUFLLENBQUMsWUFBWSxJQUFJLElBQUk7WUFDeEMsTUFBTSxFQUFFLEtBQUssQ0FBQyxNQUFNLElBQUksSUFBSTtZQUM1QixJQUFJLEVBQUUsS0FBSyxDQUFDLElBQUksSUFBSSxJQUFJO1lBQ3hCLEtBQUssRUFBRSxLQUFLLENBQUMsS0FBSyxJQUFJLElBQUk7WUFDMUIsY0FBYyxFQUFFLEtBQUssQ0FBQyxjQUFjLElBQUksSUFBSTtZQUM1QyxTQUFTLEVBQUUsS0FBSyxDQUFDLFNBQVMsSUFBSSxJQUFJO1lBQ2xDLFdBQVcsRUFBRSxLQUFLLENBQUMsV0FBVyxJQUFJLElBQUk7WUFDdEMsU0FBUyxFQUFFLEtBQUssQ0FBQyxTQUFTLElBQUksSUFBSTtZQUNsQyxZQUFZLEVBQUUsS0FBSyxDQUFDLFlBQVksSUFBSSxJQUFJO1lBQ3hDLGNBQWMsRUFBRSxLQUFLLENBQUMsY0FBYyxJQUFJLElBQUk7WUFDNUMsU0FBUyxFQUFFLEtBQUssQ0FBQyxTQUFTLElBQUksSUFBSTtZQUNsQyxTQUFTLEVBQUUsS0FBSyxDQUFDLFNBQVMsSUFBSSxJQUFJO1lBQ2xDLElBQUksRUFBRSxLQUFLLENBQUMsSUFBSSxJQUFJLElBQUk7WUFDeEIsUUFBUSxFQUFFLEtBQUssQ0FBQyxRQUFRLElBQUksSUFBSTtZQUNoQyxPQUFPLEVBQUUsS0FBSyxDQUFDLE9BQU8sSUFBSSxJQUFJO1lBQzlCLGFBQWEsRUFBRSxLQUFLLENBQUMsYUFBYSxJQUFJLElBQUk7U0FDM0MsQ0FBQyxDQUFBO0lBQ0osQ0FBQztJQUVELEtBQUssQ0FBQyx5QkFBeUIsQ0FBQyxLQUFhLEVBQUUsUUFBZ0IsRUFBRSxFQUFXO1FBQzFFLHFDQUFxQztRQUNyQyxNQUFNLE1BQU0sR0FBRyxNQUFNLElBQUksQ0FBQyxtQkFBbUIsQ0FBQyxFQUFFLEtBQUssRUFBRSxDQUFDLENBQUE7UUFDeEQsSUFBSSxNQUFNLElBQUksTUFBTSxDQUFDLE1BQU0sR0FBRyxDQUFDLEVBQUUsQ0FBQztZQUNoQyxNQUFNLEtBQUssR0FBRyxNQUFNLENBQUMsQ0FBQyxDQUFDLENBQUE7WUFDdkIsTUFBTSxFQUFFLEdBQUcsTUFBTSxrQkFBTSxDQUFDLE9BQU8sQ0FBQyxRQUFRLEVBQUUsS0FBSyxDQUFDLGFBQWEsQ0FBQyxDQUFBO1lBQzlELElBQUksRUFBRSxFQUFFLENBQUM7Z0JBQ1AsZ0NBQWdDO2dCQUNoQyxNQUFNLElBQUksQ0FBQyxxQkFBcUIsQ0FBQztvQkFDL0IsRUFBRSxFQUFFLEtBQUssQ0FBQyxFQUFFO29CQUNaLGFBQWEsRUFBRSxJQUFJLElBQUksRUFBRTtvQkFDekIsUUFBUSxFQUFFLEVBQUUsSUFBSSxJQUFJO2lCQUNyQixDQUFDLENBQUE7Z0JBQ0YsT0FBTyxFQUFFLEdBQUcsS0FBSyxFQUFFLElBQUksRUFBRSxPQUFPLEVBQUUsQ0FBQTtZQUNwQyxDQUFDO1FBQ0gsQ0FBQztRQUVELHNDQUFzQztRQUN0QyxNQUFNLEtBQUssR0FBRyxNQUFNLElBQUksQ0FBQyxrQkFBa0IsQ0FBQyxFQUFFLEtBQUssRUFBRSxDQUFDLENBQUE7UUFDdEQsSUFBSSxDQUFDLEtBQUssSUFBSSxLQUFLLENBQUMsTUFBTSxLQUFLLENBQUMsRUFBRSxDQUFDO1lBQ2pDLE1BQU0sSUFBSSxtQkFBVyxDQUFDLG1CQUFXLENBQUMsS0FBSyxDQUFDLFlBQVksRUFBRSxxQkFBcUIsQ0FBQyxDQUFBO1FBQzlFLENBQUM7UUFFRCxNQUFNLElBQUksR0FBRyxLQUFLLENBQUMsQ0FBQyxDQUFDLENBQUE7UUFDckIsTUFBTSxFQUFFLEdBQUcsTUFBTSxrQkFBTSxDQUFDLE9BQU8sQ0FBQyxRQUFRLEVBQUUsSUFBSSxDQUFDLGFBQWEsQ0FBQyxDQUFBO1FBQzdELElBQUksQ0FBQyxFQUFFLEVBQUUsQ0FBQztZQUNSLE1BQU0sSUFBSSxtQkFBVyxDQUFDLG1CQUFXLENBQUMsS0FBSyxDQUFDLFlBQVksRUFBRSxxQkFBcUIsQ0FBQyxDQUFBO1FBQzlFLENBQUM7UUFFRCxnQ0FBZ0M7UUFDaEMsTUFBTSxJQUFJLENBQUMsb0JBQW9CLENBQUM7WUFDOUIsRUFBRSxFQUFFLElBQUksQ0FBQyxFQUFFO1lBQ1gsYUFBYSxFQUFFLElBQUksSUFBSSxFQUFFO1lBQ3pCLFFBQVEsRUFBRSxFQUFFLElBQUksSUFBSTtTQUNyQixDQUFDLENBQUE7UUFFRixPQUFPLEVBQUUsR0FBRyxJQUFJLEVBQUUsSUFBSSxFQUFFLE1BQU0sRUFBRSxDQUFBO0lBQ2xDLENBQUM7SUFFRCxLQUFLLENBQUMsb0JBQW9CLENBQUMsTUFBYyxFQUFFLE9BQXVCO1FBQ2hFLE1BQU0sS0FBSyxHQUFHLE1BQU0sSUFBSSxDQUFDLGtCQUFrQixDQUFDLEVBQUUsRUFBRSxFQUFFLE1BQU0sRUFBRSxDQUFDLENBQUE7UUFDM0QsSUFBSSxDQUFDLEtBQUssSUFBSSxLQUFLLENBQUMsTUFBTSxLQUFLLENBQUMsRUFBRSxDQUFDO1lBQ2pDLE1BQU0sSUFBSSxtQkFBVyxDQUFDLG1CQUFXLENBQUMsS0FBSyxDQUFDLFNBQVMsRUFBRSwyQkFBMkIsTUFBTSxhQUFhLENBQUMsQ0FBQTtRQUNwRyxDQUFDO1FBRUQsTUFBTSxJQUFJLEdBQUcsS0FBSyxDQUFDLENBQUMsQ0FBQyxDQUFBO1FBQ3JCLElBQUksSUFBSSxDQUFDLFdBQVcsRUFBRSxDQUFDO1lBQ3JCLE9BQU8sSUFBSSxDQUFBO1FBQ2IsQ0FBQztRQUVELE1BQU0sT0FBTyxHQUFHLE1BQU0sSUFBSSxDQUFDLG9CQUFvQixDQUFDO1lBQzlDLEVBQUUsRUFBRSxNQUFNO1lBQ1YsV0FBVyxFQUFFLElBQUk7WUFDakIsV0FBVyxFQUFFLElBQUksSUFBSSxFQUFFO1lBQ3ZCLFdBQVcsRUFBRSxPQUFPLElBQUksSUFBSTtZQUM1QixXQUFXLEVBQUUsSUFBSTtZQUNqQixXQUFXLEVBQUUsSUFBSTtZQUNqQixnQkFBZ0IsRUFBRSxJQUFJO1NBQ3ZCLENBQUMsQ0FBQTtRQUVGLE9BQU8sT0FBTyxDQUFBO0lBQ2hCLENBQUM7SUFFRCxLQUFLLENBQUMsbUJBQW1CLENBQUMsTUFBYyxFQUFFLGVBQXVCLEVBQUUsT0FBdUI7UUFDeEYsTUFBTSxLQUFLLEdBQUcsTUFBTSxJQUFJLENBQUMsa0JBQWtCLENBQUMsRUFBRSxFQUFFLEVBQUUsTUFBTSxFQUFFLENBQUMsQ0FBQTtRQUMzRCxJQUFJLENBQUMsS0FBSyxJQUFJLEtBQUssQ0FBQyxNQUFNLEtBQUssQ0FBQyxFQUFFLENBQUM7WUFDakMsTUFBTSxJQUFJLG1CQUFXLENBQUMsbUJBQVcsQ0FBQyxLQUFLLENBQUMsU0FBUyxFQUFFLDJCQUEyQixNQUFNLGFBQWEsQ0FBQyxDQUFBO1FBQ3BHLENBQUM7UUFFRCxNQUFNLE9BQU8sR0FBRyxNQUFNLElBQUksQ0FBQyxvQkFBb0IsQ0FBQztZQUM5QyxFQUFFLEVBQUUsTUFBTTtZQUNWLFdBQVcsRUFBRSxLQUFLO1lBQ2xCLGdCQUFnQixFQUFFLGVBQWU7WUFDakMsV0FBVyxFQUFFLElBQUksSUFBSSxFQUFFO1lBQ3ZCLFdBQVcsRUFBRSxPQUFPLElBQUksSUFBSTtTQUM3QixDQUFDLENBQUE7UUFFRixPQUFPLE9BQU8sQ0FBQTtJQUNoQixDQUFDO0lBRUQscUJBQXFCO0lBQ3JCLEtBQUssQ0FBQyxnQkFBZ0IsQ0FBQyxLQU90QjtRQUNDLHlGQUF5RjtRQUN6RixNQUFNLEdBQUcsR0FBRyxDQUFDLEtBQUssQ0FBQyxVQUFVLEVBQUUsS0FBSyxDQUFDLFdBQVcsRUFBRSxLQUFLLENBQUMsYUFBYSxFQUFFLEtBQUssQ0FBQyxPQUFPLENBQUMsQ0FBQyxNQUFNLENBQUMsT0FBTyxDQUFDLENBQUE7UUFDckcsSUFBSSxHQUFHLENBQUMsTUFBTSxLQUFLLENBQUMsRUFBRSxDQUFDO1lBQ3JCLE1BQU0sSUFBSSxtQkFBVyxDQUNuQixtQkFBVyxDQUFDLEtBQUssQ0FBQyxZQUFZLEVBQzlCLG9GQUFvRixDQUNyRixDQUFBO1FBQ0gsQ0FBQztRQUVELGdEQUFnRDtRQUNoRCxJQUFJLEtBQUssQ0FBQyxlQUFlLEdBQUcsQ0FBQyxJQUFJLEtBQUssQ0FBQyxlQUFlLEdBQUcsR0FBRyxFQUFFLENBQUM7WUFDN0QsTUFBTSxJQUFJLG1CQUFXLENBQ25CLG1CQUFXLENBQUMsS0FBSyxDQUFDLFlBQVksRUFDOUIsMkNBQTJDLENBQzVDLENBQUE7UUFDSCxDQUFDO1FBRUQscURBQXFEO1FBQ3JELE1BQU0sUUFBUSxHQUFHLE1BQU0sSUFBSSxDQUFDLHdCQUF3QixDQUFDO1lBQ25ELFVBQVUsRUFBRSxLQUFLLENBQUMsVUFBVSxJQUFJLFNBQVM7WUFDekMsV0FBVyxFQUFFLEtBQUssQ0FBQyxXQUFXLElBQUksU0FBUztZQUMzQyxhQUFhLEVBQUUsS0FBSyxDQUFDLGFBQWEsSUFBSSxTQUFTO1lBQy9DLE9BQU8sRUFBRSxLQUFLLENBQUMsT0FBTyxJQUFJLFNBQVM7U0FDcEMsQ0FBQyxDQUFBO1FBRUYsSUFBSSxRQUFRLElBQUksUUFBUSxDQUFDLE1BQU0sR0FBRyxDQUFDLEVBQUUsQ0FBQztZQUNwQywyREFBMkQ7WUFDM0QsTUFBTSxrQkFBa0IsR0FBRyxRQUFRLENBQUMsQ0FBQyxDQUFDLENBQUE7WUFDdEMsT0FBTyxNQUFNLElBQUksQ0FBQywwQkFBMEIsQ0FBQztnQkFDM0MsRUFBRSxFQUFFLGtCQUFrQixDQUFDLEVBQUU7Z0JBQ3pCLGVBQWUsRUFBRSxLQUFLLENBQUMsZUFBZTtnQkFDdEMsUUFBUSxFQUFFLEtBQUssQ0FBQyxRQUFRLElBQUksa0JBQWtCLENBQUMsUUFBUTthQUN4RCxDQUFDLENBQUE7UUFDSixDQUFDO1FBRUQsT0FBTyxNQUFNLElBQUksQ0FBQywwQkFBMEIsQ0FBQztZQUMzQyxVQUFVLEVBQUUsS0FBSyxDQUFDLFVBQVUsSUFBSSxJQUFJO1lBQ3BDLFdBQVcsRUFBRSxLQUFLLENBQUMsV0FBVyxJQUFJLElBQUk7WUFDdEMsYUFBYSxFQUFFLEtBQUssQ0FBQyxhQUFhLElBQUksSUFBSTtZQUMxQyxPQUFPLEVBQUUsS0FBSyxDQUFDLE9BQU8sSUFBSSxJQUFJO1lBQzlCLGVBQWUsRUFBRSxLQUFLLENBQUMsZUFBZTtZQUN0QyxRQUFRLEVBQUUsS0FBSyxDQUFDLFFBQVEsSUFBSSxJQUFJO1NBQ2pDLENBQUMsQ0FBQTtJQUNKLENBQUM7SUFFRCxLQUFLLENBQUMsZ0JBQWdCLENBQUMsWUFBb0IsRUFBRSxLQUc1QztRQUNDLE1BQU0sV0FBVyxHQUFHLE1BQU0sSUFBSSxDQUFDLHdCQUF3QixDQUFDLEVBQUUsRUFBRSxFQUFFLFlBQVksRUFBRSxDQUFDLENBQUE7UUFDN0UsSUFBSSxDQUFDLFdBQVcsSUFBSSxXQUFXLENBQUMsTUFBTSxLQUFLLENBQUMsRUFBRSxDQUFDO1lBQzdDLE1BQU0sSUFBSSxtQkFBVyxDQUFDLG1CQUFXLENBQUMsS0FBSyxDQUFDLFNBQVMsRUFBRSx1QkFBdUIsWUFBWSxhQUFhLENBQUMsQ0FBQTtRQUN0RyxDQUFDO1FBRUQsdUNBQXVDO1FBQ3ZDLElBQUksS0FBSyxDQUFDLGVBQWUsS0FBSyxTQUFTLEVBQUUsQ0FBQztZQUN4QyxJQUFJLEtBQUssQ0FBQyxlQUFlLEdBQUcsQ0FBQyxJQUFJLEtBQUssQ0FBQyxlQUFlLEdBQUcsR0FBRyxFQUFFLENBQUM7Z0JBQzdELE1BQU0sSUFBSSxtQkFBVyxDQUNuQixtQkFBVyxDQUFDLEtBQUssQ0FBQyxZQUFZLEVBQzlCLDJDQUEyQyxDQUM1QyxDQUFBO1lBQ0gsQ0FBQztRQUNILENBQUM7UUFFRCxPQUFPLE1BQU0sSUFBSSxDQUFDLDBCQUEwQixDQUFDO1lBQzNDLEVBQUUsRUFBRSxZQUFZO1lBQ2hCLGVBQWUsRUFBRSxLQUFLLENBQUMsZUFBZTtZQUN0QyxRQUFRLEVBQUUsS0FBSyxDQUFDLFFBQVE7U0FDekIsQ0FBQyxDQUFBO0lBQ0osQ0FBQztJQUVELEtBQUssQ0FBQyxnQkFBZ0IsQ0FBQyxZQUFvQjtRQUN6QyxNQUFNLFdBQVcsR0FBRyxNQUFNLElBQUksQ0FBQyx3QkFBd0IsQ0FBQyxFQUFFLEVBQUUsRUFBRSxZQUFZLEVBQUUsQ0FBQyxDQUFBO1FBQzdFLElBQUksQ0FBQyxXQUFXLElBQUksV0FBVyxDQUFDLE1BQU0sS0FBSyxDQUFDLEVBQUUsQ0FBQztZQUM3QyxNQUFNLElBQUksbUJBQVcsQ0FBQyxtQkFBVyxDQUFDLEtBQUssQ0FBQyxTQUFTLEVBQUUsdUJBQXVCLFlBQVksYUFBYSxDQUFDLENBQUE7UUFDdEcsQ0FBQztRQUVELE1BQU0sSUFBSSxDQUFDLDBCQUEwQixDQUFDLFlBQVksQ0FBQyxDQUFBO1FBQ25ELE9BQU8sRUFBRSxPQUFPLEVBQUUsSUFBSSxFQUFFLENBQUE7SUFDMUIsQ0FBQztDQUNGO0FBRUQsa0JBQWUsc0JBQXNCLENBQUEifQ==