import { Pool } from "pg"
import { VENDOR_MODULE } from "../modules/vendor"
import VendorModuleService from "../modules/vendor/service"
import {
  buildVendorCommissionInvoice,
  previousCalendarMonthWindow,
  saveMonthlyCommissionInvoice,
} from "../lib/vendor-commission-invoice"
import { hasPasswordResetMailerConfig } from "../lib/password-reset/config"
import { sendTransactionalEmail } from "../lib/password-reset/mailer"

/**
 * On the 7th of every month (IST), snapshot each vendor's previous-month
 * commission/tax invoice so one-click download is ready.
 *
 * Cron is UTC: 18:35 on the 6th ≈ 00:05 IST on the 7th.
 */
export default async function generateMonthlyCommissionInvoicesJob(container: any) {
  const logger = container.resolve("logger")

  if (!process.env.DATABASE_URL) {
    logger.warn("[commission-invoice-job] DATABASE_URL missing")
    return
  }

  const now = new Date()
  const istParts = new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Kolkata",
    day: "2-digit",
    hour: "2-digit",
    hour12: false,
  }).formatToParts(now)
  const day = Number(istParts.find((p) => p.type === "day")?.value || 0)
  const hour = Number(istParts.find((p) => p.type === "hour")?.value || 0)

  // Only run during early hours on the 7th IST (job may fire once around midnight).
  if (day !== 7 || hour > 6) {
    logger.info(`[commission-invoice-job] skip istDay=${day} istHour=${hour}`)
    return
  }

  const month = previousCalendarMonthWindow(now)
  const pool = new Pool({ connectionString: process.env.DATABASE_URL })
  const vendorService = container.resolve(VENDOR_MODULE) as VendorModuleService

  let vendors: Array<Record<string, unknown>> = []
  try {
    const listed = await vendorService.listVendors({})
    vendors = Array.isArray(listed) ? listed : []
  } catch (error: any) {
    logger.warn(`[commission-invoice-job] list vendors failed: ${error?.message}`)
    await pool.end().catch(() => undefined)
    return
  }

  logger.info(
    `[commission-invoice-job] generating ${month.periodKey} for ${vendors.length} vendor(s)`
  )

  let saved = 0
  let emailed = 0

  for (const vendor of vendors) {
    const vendorId = String(vendor.id || "")
    if (!vendorId) continue
    const status = String(vendor.status || "").toLowerCase()
    if (status && status !== "approved" && status !== "active") continue

    try {
      const payload = await buildVendorCommissionInvoice(
        vendorId,
        vendor,
        pool,
        "last_month",
        undefined,
        undefined,
        { markAutoGenerated: true }
      )
      if ("error" in payload) continue

      await saveMonthlyCommissionInvoice(pool, vendorId, month.periodKey, payload)
      saved += 1

      const email = String(vendor.email || "").trim()
      if (email && hasPasswordResetMailerConfig() && payload.orders.length > 0) {
        await sendTransactionalEmail({
          to: email,
          subject: `OWEG commission invoice ready · ${month.label}`,
          heading: "Your monthly commission invoice is ready",
          intro: `Hi ${payload.billed_to.display_name}, your Commission/Tax Invoice for ${month.label} has been generated.`,
          paragraphs: [
            `Invoice number: ${payload.invoice_number}`,
            `Orders: ${payload.orders.length}`,
            `Invoice total: ₹${payload.totals.grand_total.toFixed(2)}`,
            "Open Vendor Portal → Commission Invoice → Last month, then click Download all (PDF).",
          ],
          previewText: `Commission invoice ${payload.invoice_number} is ready`,
        })
        emailed += 1
      }
    } catch (error: any) {
      logger.warn(
        `[commission-invoice-job] vendor=${vendorId}: ${error?.message || error}`
      )
    }
  }

  await pool.end().catch(() => undefined)
  logger.info(
    `[commission-invoice-job] done period=${month.periodKey} saved=${saved} emailed=${emailed}`
  )
}

export const config = {
  name: "generate-monthly-commission-invoices",
  // 18:35 UTC on the 6th ≈ 00:05 IST on the 7th
  schedule: "35 18 6 * *",
}
